print ("\t\tCHEAP PRICE SUPERMARKET")
print ("-----------------------------------------------------------\n")
print (" Date:")
print (" Items \t\t price\t quantity \t amount")
print (" Bread \t\t 6000")
print (" Bluband big \t 10000")
print (" suger \t\t 6000")
print (" Total amount \n")
print ("\t Thank you our esteemed customer, come again.")
print ("------------------------------------------------------------")